### PR TITLE
ui improve 2. made menu page match more like tabs

### PR DESCRIPTION
**Pull request by s2cheung**
image

### CODE REVIEW

**Comment by cqvu** [comment]
Weird rendering for saved tabs
image

**Comment by abhimanyuthube** [comment]
> Weird rendering for saved tabs
> image

this has been fixed in a recently merged PR

**Comment by s2cheung** [comment]
Fixed the button. Not sure how to reproduce the saved tab rendering

**Comment by abhimanyuthube** [comment]
can we add a message below the Tab Groups header only when there are no tabgroups? "Your tab groups will appear here. Click the plus button above to add a new tab group." Or something like that.

And maybe for the popup: "Your tab groups will appear here. Open the Potato tab menu to add a new tab group."

**Comment by s2cheung** [comment]
image

**Comment by s2cheung** [comment]
Added this tab group is empty. Drag a tab here.

**Comment by abhimanyuthube** [comment]
The text in the empty tabgroup is a nice addition. What I was actually referring to is when the whole tabgroups section of the screen is empty. Like this:

image

Some text here telling the user to click on the plus button to add a group would be nice. Similar idea for the Popup.

**Comment by s2cheung** [comment]
oof. alright here's the change
Screen Shot 2020-06-07 at 11 44 41 PM

**Pull request merged**
